sudo: required
language: python
service:
  - docker
before_install:
# Downloading Azure CLI and install script by running curl
  - curl https://azurecliprod.blob.core.windows.net/install | bash
script:
  - az --version