sudo: required
language: generic
env:
  global:
    - AZ_REPO=$(lsb_release -cs)
service:
  - docker
before_install:
  # Downloading Azure CLI and install script
  # Get packages needed for the install process
  - sudo apt-get update
  - sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
  # Download and install the Microsoft signing key
  - curl -sL https://packages.microsoft.com/keys/microsoft.asc | 
       gpg --dearmor | 
       sudo tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null
  # Add the Azure CLI software repository
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | 
       sudo tee /etc/apt/sources.list.d/azure-cli.list
  # Update repository information and install the azure-cli package
  - sudo apt-get update
  - sudo apt-get install azure-cli
  # Install Kubectl command
  - sudo az aks install-cli     
script:
  - sudo az login --service-principal -u $AZURE_SP_USERNAME -p AZURE_SP_PASSWORD$ --tenant $AZURE_SP_TENANT
  - sudo az aks get-credentials --resource-group $AZURE_AKS_RESOURCE_GROUP --name $Azure_AKS_Name
  - kubectl get nodes