sudo: required
language: python
service:
  - docker
before_install:
# Downloading Azure CLI and install script by running curl
  - sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 417A0893
  - sudo apt-get install apt-transport-https
  - sudo apt-get update && sudo apt-get install azure-cli
script:
  - az --version